Making first connection with NewsAPI
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #19
Opened 2021-01-02 16:49 UTC by adam-kostuch

2021-01-02 19:41 UTC, jkopyto commented
Przypisz proszę pull requesta do projektu i z `Linked issues` wybierz odpowiednie issue

2021-01-02 19:44 UTC, jkopyto commented on src/services/NewsApiService/NewsApiService.js
> +    const res = await this.get(`${this.creds.API_LINK}&q=*`)
```suggestion
    const res = await this.get(`${this.creds.API_LINK}&q=*`).then(res => res.json())
```

2021-01-02 19:45 UTC, jkopyto requested changes

2021-01-02 19:45 UTC, jkopyto commented on src/services/NewsApiService/NewsApiService.js
> +    const res = await this.get(`${this.creds.API_LINK}&language=pl&q=*`)
jak wyżej

2021-01-02 19:45 UTC, jkopyto commented on src/services/NewsApiService/NewsApiService.js
> +    const res = await this.get(`${this.creds.API_LINK}&q=health`)
i tutaj

2021-01-02 19:45 UTC, jkopyto commented
I jeszcze warto by było popisać testy

2021-01-07 10:52 UTC, jkopyto requested changes

2021-01-07 10:52 UTC, jkopyto commented on src/subpages/newsSubpage/news.html
> +=======
A cóż to za artefakt

2021-01-07 10:52 UTC, jkopyto commented on src/index.js
>  const ONE_SECOND_MILLIS = 1000
To można wywalić

2021-01-10 01:34 UTC, kubaszajna commented
Warto dodać od samego początku klasy w metodologii BEM do generowanego kodu oraz poszczególne News'y warto wrzucić w tag <article> wykorzystując możliwości HTML5

2021-01-11 18:09 UTC, jkopyto requested changes

2021-01-11 18:09 UTC, jkopyto commented on .history/src/services/NewsApiService/NewsApiService_20210102142541.js
> +    // var today = new Date()
jak niepotrzebne to usunąć

2021-01-11 18:09 UTC, jkopyto commented on .history/src/services/NewsApiService/NewsApiService_20210102142541.js
> +  /* async getPolandNews() {
i tu

2021-01-11 18:09 UTC, jkopyto commented on src/services/NewsApiService/NewsApiService.js
> +import process from "process"
Do usunięcia. Nie jest nam to potrzebne

2021-01-11 18:09 UTC, jkopyto commented on src/services/NewsApiService/NewsApiService.js
> +    return await this.get(`${this.creds.API_LINK}&q=*`).then((res) =>
Jest do dobrze napisane, ale dla czytelności widziałem, że praktykuje się raczej przypisane tego awaita do consta `const res = await this.get...` i zwracanie samego res `return res`

2021-01-11 18:09 UTC, jkopyto commented on .history/src/services/NewsApiService/NewsApiService_20210102145233.js
> +    console.log(this.creds.API_KEY)
bez console logów na prodzie. W ogóle dziwne, że wciąż ten .history znajduje się tutaj mimo, że jest dodany do .gitignore

2021-01-12 18:12 UTC, jkopyto approved these changes

2021-01-12 18:12 UTC, jkopyto commented
Rozwiąż konfilkt u siebie i zmergujemy ;)

2021-01-12 21:34 UTC, jkopyto approved these changes

2021-01-12 21:34 UTC, merged