Feature/weather service
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #20
Opened 2021-01-04 21:43 UTC by kgutka

2021-01-04 21:47 UTC, kgutka commented on src/app/App.js
> +export const App = async ({ options }) => {
Intentionally left unused parameter - options (it was present on master I didn't want to remove it, it is the only reason why CI ESLint failed)

2021-01-06 11:04 UTC, jkopyto requested changes

2021-01-06 11:04 UTC, jkopyto commented on package.json
> +    "process": "^0.11.10",
Do czego ta libka?

2021-01-06 11:04 UTC, jkopyto commented on src/index.js
> +    // options: { swApiBaseUrl: SW_API_BASE_URL, quizMaxTime: QUIZ_MAX_TIME },
Niech zostanie samo App()

2021-01-06 11:04 UTC, jkopyto commented on styles/App.css
> +  font-weight: bold;
W folderze `subpages/weatherdataSubpage` utwórz nowy arkusz CSS i tam wrzuć rzeczy dla Twojej podstrony

2021-01-06 11:04 UTC, jkopyto commented on index.html
> +    <div id="weather">
To na pewno nie bedzie w tym pliku. W folderze `subpages/weatherdataSubpage` utworzysz nowy plik html i tam wrzucisz swój content. A jak bedzie routing zmergowany to się podepnie wtedy Twój plik

2021-01-06 11:05 UTC, jkopyto commented on src/app/App.js
> +export const App = async ({ options }) => {
Do usunięcia te `{ options }`. I tak jak mówiłem na spotkaniu wprowdzającym - przy review możemy śmiało pisać po polsku. Angielski zostawiamy dla wiki i issuesów

2021-01-06 11:06 UTC, jkopyto commented
Z kolumny po prawej przypisz prosze tego pull requesta do projektu i do odpowiedniego issue

2021-01-06 20:37 UTC, kgutka commented on src/app/App.js
> +export const App = async ({ options }) => {
Zrobione

2021-01-06 20:38 UTC, kgutka commented on src/services/WeatherService/WeatherApiService.js
> +  // }
zrobione

2021-01-06 20:43 UTC, kgutka commented on src/subpages/weatherdataSubpage/WeatherSubpage.js
> +      const iconCode = weatherRes.weather[0].icon
zrobione

2021-01-06 20:44 UTC, kgutka commented on src/subpages/weatherdataSubpage/WeatherSubpage.js
> +      const iconUrl = `http://openweathermap.org/img/w/${iconCode}.png`
zrobione

2021-01-06 21:33 UTC, kgutka commented on src/index.js
> +    // options: { swApiBaseUrl: SW_API_BASE_URL, quizMaxTime: QUIZ_MAX_TIME },
zrobione

2021-01-06 22:08 UTC, kgutka commented on package.json
> +    "process": "^0.11.10",
Webstorm mi podpowiedział, żeby ją zainstalować przy pierwszym uruchamianiu projektu i dałam ok, teraz sprawdziłam i bez też działa, więc już usuwam - zrobione.

2021-01-06 23:13 UTC, kgutka commented on index.html
> +    <div id="weather">
Zrobione

2021-01-07 10:48 UTC, jkopyto requested changes

2021-01-07 10:48 UTC, jkopyto commented on src/services/NewsApiService/CryptoCurrency.service.js
> +      .catch((e) => e.message)
A cóż to się tu podziało? Czemu są tu rzeczy z CryptoApi?

2021-01-07 10:48 UTC, jkopyto commented on src/index.js
> +provider.provide("weatherSubpage", new WeatherSubpage())
Czemu `weatherSubpage` jest rejestrowany do providera?

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.css
> +  background-color: #eaeaea;
Takie kolorki do do zmiennych jakiś przypiszmy

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.css
> +  margin: 1%;
Lepiej jakby tu była jakaś wartość w `px`

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.css
> +  margin: 2%;
jak wyżej

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const updatePage = async (city = "Berlin") => {
Niech to będzie metoda klasy

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const weatherApi = provider.get("weatherApiService")
Do constructora

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const weatherContentDiv = document.querySelector("#weather-content")
Do konstruktora

2021-01-07 10:48 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +      function getIconUrl(iconCode) {
To też można wynieść poza funkcje `updatePage`

2021-01-07 10:48 UTC, jkopyto commented on src/services/Router.js
> +        provider.get("weatherSubpage").render()
Drugi `switch case` jest niepotrzebny. Lepiej umieść to po prostu w case `weather` pod `content`. Można utworzyć nową zmienną w `loadContent` np. `let script` i wtedy case `weather` bedzie wyglądał tak:
```
case "weather":
        content = weatherSubpage
        script = provider.get("weatherSubpage").render
        break
```
i będzie też `this.updateSlot(content, script)`

i na koniec:
````
updateSlot(content, script) {
    this.slot.innerHTML = content
    script && script()
  }
```

2021-01-07 15:28 UTC, kgutka commented on styles/App.css
> +  font-weight: bold;
zrobione

2021-01-07 15:39 UTC, kgutka commented on src/index.js
> +provider.provide("weatherSubpage", new WeatherSubpage())
już się tego pozbyłam

2021-01-07 15:41 UTC, kgutka commented on src/services/NewsApiService/CryptoCurrency.service.js
> +      .catch((e) => e.message)
po zmergowaniu z mastera do mojego brancha zmiany się same dodały (najprawdopodobniej IDE mi je dodatkowo sformatowało)

2021-01-07 15:48 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const updatePage = async (city = "Berlin") => {
zrobione

2021-01-07 15:48 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const weatherApi = provider.get("weatherApiService")
zrobione

2021-01-07 16:06 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const weatherContentDiv = document.querySelector("#weather-content")
zrobione

2021-01-07 21:07 UTC, jkopyto commented on src/services/NewsApiService/CryptoCurrency.service.js
> +      .catch((e) => e.message)
Miałem na myśli cały plik. Ale to już z Mateuszem wyjaśniłem, skąd takie rzeczy ;)

2021-01-07 22:07 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.css
> +  background-color: #eaeaea;
zrobione

2021-01-07 22:07 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.css
> +  margin: 1%;
zrobione

2021-01-07 22:09 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.css
> +  margin: 2%;
zrobione

2021-01-07 22:10 UTC, kgutka commented on src/services/Router.js
> +        provider.get("weatherSubpage").render()
zrobione

2021-01-07 22:10 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +      function getIconUrl(iconCode) {
zrobione

2021-01-08 10:53 UTC, jkopyto requested changes

2021-01-08 10:53 UTC, jkopyto commented on src/services/Router.js
> +        script = () => new WeatherSubpage().render()
```suggestion
        script = new WeatherSubpage().render
```

2021-01-08 10:58 UTC, kgutka commented on src/services/Router.js
> +        script = () => new WeatherSubpage().render()
na początku tak miałam, tylko jest wtedy problem z zapytaniami, ponieważ skrypt ( script() )odwołuje się do Routera zamiast do WeatherSubpage, dostaję wtedy błąd: 
Uncaught (in promise) TypeError: Cannot read property 'updatePage' of undefined

2021-01-08 10:59 UTC, jkopyto commented on src/services/Router.js
> +        script = () => new WeatherSubpage().render()
Dobra, to niech zostanie tak jak było ;)

2021-01-08 10:59 UTC, merged