Feature/Food Api Service
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #23
Opened 2021-01-06 21:55 UTC by kacperzolkiewski

2021-01-07 10:22 UTC, jkopyto requested changes

2021-01-07 10:22 UTC, jkopyto commented on package.json
> +    "node-fetch": "^2.6.1",
Ta libka jest niepotrzebna

2021-01-07 10:22 UTC, jkopyto commented on src/services/FoodApiService/__tests__/foodApiTests.test.js
> +  })
Testy wyglądają super. Zastanowiłbym się jednak nad opisami przy `it`. Bo teraz te opisy sugerują, że testujemy bezpośrednio endpointy w FoodAPI, a w rzeczywiści sprawdzamy jedynie implementacje metod w serwisie. W `it` radziłbym napisać coś w stylu `it("Returns an object", async() => ...` albo `it("Returns a string with ingredient", async() =>...`

2021-01-07 10:22 UTC, jkopyto commented on test/foodApitests.test.js
> +})
Ten plik do usunięcia

2021-01-07 10:22 UTC, jkopyto commented on test/sampleJavaScript.spec.js
> -});
Ten plik też można usunąć

2021-01-07 10:22 UTC, jkopyto commented on .vscode/launch.json
> +}
A cóż to? Weź dodaj folder .vscode do .gitignore

2021-01-08 10:50 UTC, kacperzolkiewski commented on .vscode/launch.json
> +}
Zrobione

2021-01-08 10:55 UTC, jkopyto requested changes
Jak tylko build bedzie przechodził to zmerguje

2021-01-08 13:01 UTC, jkopyto approved these changes

2021-01-08 13:01 UTC, merged