Feature/sport data api
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #26
Opened 2021-01-10 01:18 UTC by kubaszajna

Created Sport Data subpage with styles and refactored script

2021-01-10 20:08 UTC, jkopyto requested changes

2021-01-10 20:08 UTC, jkopyto commented on src/services/SportApiService/SportApiService.js
> +/* eslint-disable no-undef */
Bezpieczniej bez tego

2021-01-10 20:08 UTC, jkopyto commented on src/services/SportApiService/SportApiService.js
> +    let data = await res.json()
```suggestion
    const res = await this.get(
      `${this.creds.API_BASE_LINK}${event}${this.creds.API_KEY}&season_id=619`
    ).then(res => res.json())
    
    return res
```

Podobnie w pozostałych metodach

2021-01-10 20:08 UTC, jkopyto commented on src/subpages/sportSubpage/styles.css
> +  /* box-shadow: 0 16px 12px #0e0e23; */
Jak niepotrzebne to do wywalenia

2021-01-10 20:08 UTC, jkopyto commented on src/subpages/sportSubpage/styles.css
> +  /* background: #11132c; */
To też

2021-01-10 20:08 UTC, jkopyto commented on src/subpages/sportSubpage/styles.css
> +  /* background: #1a1b3c; */
Ten i dalsze też

2021-01-10 20:08 UTC, jkopyto commented on src/subpages/sportSubpage/SportData.js
> +}
Nie pasuje mi trochę to, że część osób pisze swoje skrypty do podstron w formie klas, a tutaj widzę funkcję. Wolałbym jednak, żeby to zostało ujednolicone

2021-01-10 20:08 UTC, jkopyto commented on src/index.js
> +window.onload = () => SportApiFunction()
Funkcja powinna być odpalana z poziomu routera

2021-01-17 14:50 UTC, kubaszajna commented
Zrobione. Utworzona klasa + dodane testy + podpięte style + poprawione błędy

2021-01-18 10:47 UTC, jkopyto requested changes

2021-01-18 10:47 UTC, jkopyto commented on .env
> +=======
artefakty po rebasie pozostały

2021-01-18 10:47 UTC, jkopyto commented on index.html
> +<<<<<<< HEAD
i tu

2021-01-18 10:47 UTC, jkopyto commented on src/services/SportApiService/SportApiService.js
> +/* eslint-disable no-undef */
to wciaz jest

2021-01-18 10:47 UTC, jkopyto commented on src/index.js
> +<<<<<<< HEAD
poprzeglądaj pliki za tymi artefaktami bo sporo ich jest

2021-01-18 11:28 UTC, closed without merging