Feature/weather forecast
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #33
Opened 2021-01-13 13:53 UTC by kgutka

Dodanie prognozy pogody na 8 najbliższych dni

2021-01-13 21:01 UTC, jkopyto requested changes

2021-01-13 21:01 UTC, jkopyto commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const iconUrlForecastDay7 = this.getIconUrl(iconCodeForecastDay7)
nie potrzebujesz tworzyć tych wszystkich constów, jeśli i tak tylko raz z tego skorzystasz później przy pakowaniu tego do stringa. Najlepsza by była osobna funkcja, która pozwoli Ci tworzyć cały `innerHTML`. I to taka funkcja w osobnym pliku, bo tu już po prostu za dużo i ciężko się to czyta

2021-01-14 20:28 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const [dateDay8, dayOfWeekDay8] = this.getDateAndDayOfWeek(8)
zrobione  - metoda getForecastedData() w klasie WeatherData

2021-01-14 20:28 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const iconUrlForecastDay7 = this.getIconUrl(iconCodeForecastDay7)
jak poprzednie - metoda w klasie getForecastedData(forecastWeatherResults)

2021-01-14 20:30 UTC, kgutka commented on src/subpages/weatherSubpage/WeatherSubpage.js
> +    const iconUrlForecastDay7 = this.getIconUrl(iconCodeForecastDay7)
do `innerhtml` metoda - `renderHTML()` w klasie `WeatherData`

2021-01-15 16:32 UTC, jkopyto approved these changes

2021-01-15 16:32 UTC, merged