Creating Js, Html and CSS files in subpage. Feature/food api subpage
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #37
Opened 2021-01-14 13:41 UTC by kacperzolkiewski

2021-01-14 19:27 UTC, jkopyto requested changes

2021-01-14 19:27 UTC, jkopyto commented on src/subpages/foodSubpage/food.html
> +<h1 class="title">Find your favourite food</h1>
Dobrze by było dla porządku, żeby całość była zwrapowana w jeden tag. W tej chwili jest:
```
<h1>Find your favourite food</h1>
<div class="container>
...
</div>
```
a pasowałoby:
```
<div class="nice-class-name">
   <h1>Find your favourite food</h1>
   <div class="container">
   ...
   </div>
</div>
```
albo przenieść tego `<h1 />` do środka `<div class="container" />`

2021-01-17 10:08 UTC, kacperzolkiewski commented on src/subpages/foodSubpage/food.html
> +<h1 class="title">Find your favourite food</h1>
Zrobione

2021-01-17 13:31 UTC, jkopyto approved these changes

2021-01-17 13:31 UTC, merged