Feature/crypto currency page
jkopyto/CodersCamp2020.Project.JavaScript.NewsService pull request #41
Opened 2021-01-16 12:42 UTC by mateuszCabala95

create crypto currency subpage

2021-01-16 20:46 UTC, jkopyto requested changes

2021-01-16 20:46 UTC, jkopyto commented on src/subpages/cryptocurrencySubpage/CryptoCurrency.js
> +    await this._currencyAPI.exchangeCoinToUSD(coinId, amountOfCoins).then(r => r)
```suggestion
    await this._currencyAPI.exchangeCoinToUSD(coinId, amountOfCoins)
```
to powinno wystarczyć

2021-01-16 20:46 UTC, jkopyto commented on src/subpages/cryptocurrencySubpage/CryptoCurrency.js
> +  renderModal = (clickedCoin) => {
a może lepiej zrobić nową klaskę `ModalView` gdzieś w osobnym pliku i tam przenieść całą jego funkcjonalność

2021-01-18 11:32 UTC, jkopyto commented
Prosze żeby rozwiązać te konflikty i zgłoszoną przeze mnie propozycje jak już zrobiona

2021-01-18 15:46 UTC, mateuszCabala95 commented
błędy pochodzą z mockowancyh odpowiedzi do testów

2021-01-18 15:46 UTC, merged